'use strict';
const $=id=>document.getElementById(id);
let chosen=[], path='', batch=null, xhr=null, cancelled=false, mode='files', urls=[], connected=false, editing=false, destination='';
const uid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
async function recover(){const pending=(await api('/web/uploads')).find(b=>['waiting','accepted'].includes(b.state));$('recover').hidden=!pending;if(pending){message('上一批传输未完成，可结束后重新发送。');$('recover').onclick=async()=>{try{await api('/web/uploads/'+pending.id,'DELETE');$('recover').hidden=true;message('可以重新选择并发送')}catch(e){message(e.message)}}}}
function message(s){$('message').textContent=s}
async function api(url,method='GET',value){const r=await fetch(url,{method,headers:value?{'Content-Type':'application/json'}:{},body:value?JSON.stringify(value):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data}
function page(id){for(const v of ['login','send','files','settings','progress'])$(v).hidden=v!==id;document.body.classList.toggle('transferring',id==='progress');$('sendTab').classList.toggle('active',id==='send');$('settingsTab').classList.toggle('active',id==='settings')}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];$('selected').replaceChildren();$('summary').textContent=chosen.length?'文件：'+chosen.length+' · 大小：'+size(chosen.reduce((n,f)=>n+f.size,0)):'尚未选择文件';$('edit').hidden=!chosen.length;$('edit').textContent=editing?'完成':'编辑';$('clear').hidden=!chosen.length||!editing;chosen.forEach((f,i)=>{const row=document.createElement('div');row.className='file-card';if(f.type.startsWith('image/')){const img=document.createElement('img');img.src=URL.createObjectURL(f);urls.push(img.src);row.append(img)}else{const icon=document.createElement('span');icon.className='file-icon';icon.textContent=/\.(mp3|aiyuepack)$/i.test(f.name)?'♫':'▤';row.append(icon)}const label=document.createElement('span');label.className='file-name';label.textContent=f.webkitRelativePath||f.name;label.title=label.textContent;const bytes=document.createElement('span');bytes.className='file-size';bytes.textContent=size(f.size);const remove=document.createElement('button');remove.textContent='删除';remove.hidden=!editing;remove.onclick=()=>{chosen.splice(i,1);render()};row.append(label,bytes,remove);$('selected').append(row)})}
function select(files,m='files'){chosen=Array.from(files);mode=m;render();message('')}
$('choose').onclick=()=>$('fileInput').click();$('folder').onclick=()=>$('folderInput').click();
for(const id of ['fileInput','folderInput'])$(id).onchange=e=>{select(e.target.files);e.target.value=''};
async function droppedFiles(dataTransfer){const items=Array.from(dataTransfer.items||[]);const result=[];async function visit(entry,prefix=''){if(entry.isFile){await new Promise(resolve=>entry.file(file=>{try{Object.defineProperty(file,'webkitRelativePath',{value:prefix+file.name})}catch{}result.push(file);resolve()},resolve));return}if(entry.isDirectory){const reader=entry.createReader();await new Promise(resolve=>reader.readEntries(async entries=>{for(const child of entries)await visit(child,prefix+entry.name+'/');resolve()}))}}for(const item of items){const entry=item.webkitGetAsEntry?.();if(entry)await visit(entry);else if(item.kind==='file'){const file=item.getAsFile();if(file)result.push(file)}}return result.length?result:Array.from(dataTransfer.files||[])}
$('clear').onclick=()=>{chosen=[];render()};const drop=$('drop');drop.ondragenter=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragover=e=>e.preventDefault();drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=async e=>{e.preventDefault();drop.classList.remove('dragging');select(await droppedFiles(e.dataTransfer))};
 $('connect').onclick=async()=>{try{await api('/web/session','POST',{code:$('code').value});$('code').value='';connected=true;page('send');message('已连接');await recover();const info=await api('/web/info');$('version').textContent='版本 '+info.version+' · 浏览器已连接手机'}catch(e){message(e.message)}};
$('sendTab').onclick=()=>{if(!batch)page(connected?'send':'login')};$('filesTab').onclick=()=>{if(!batch&&connected)load()};
async function load(){try{const list=await api('/web/files?path='+encodeURIComponent(path));page('files');$('path').textContent=path||'爱乐互传';$('listing').replaceChildren();for(const f of list){const row=document.createElement('div');row.className='row';const label=document.createElement('div');label.textContent=(f.directory?'📁 ':'📄 ')+f.name+(f.directory?'':' · '+size(f.size));const action=document.createElement(f.directory?'button':'a');action.textContent=f.directory?'打开':'下载';if(f.directory)action.onclick=()=>{path=f.path;load()};else{action.href='/web/download?path='+encodeURIComponent(f.path);action.download=f.name}row.append(label,action);$('listing').append(row)}}catch(e){message(e.message)}}
$('reload').onclick=load;$('up').onclick=()=>{path=path.split('/').slice(0,-1).join('/');load()};$('mkdir').onclick=async()=>{const name=prompt('文件夹名称');if(!name)return;try{await api('/web/folders','POST',{path:(path?path+'/':'')+name});await load()}catch(e){message(e.message)}};
function upload(file,id,row,previous,total){return new Promise((resolve,reject)=>{xhr=new XMLHttpRequest();xhr.open('PUT','/web/uploads/'+batch+'/'+id);xhr.upload.onprogress=e=>{row.progress.value=e.loaded/file.size||0;$('total').value=(previous+e.loaded)/total||0;row.status.textContent='正在传输 '+size(e.loaded)+' / '+size(file.size)};xhr.onload=()=>{if(xhr.status===200){row.progress.value=1;row.status.textContent='已保存到文件 › 爱乐互传';resolve()}else reject(Error('保存失败，请重试'))};xhr.onerror=()=>reject(Error('连接中断'));xhr.onabort=()=>reject(Error('已取消'));xhr.timeout=0;xhr.ontimeout=()=>reject(Error('传输超时'));xhr.send(file)})}
 $('sendNow').onclick=async()=>{if(!chosen.length){message('请至少选择一个文件。');return}cancelled=false;const files=chosen;
page('progress');$('done').hidden=true;$('cancel').hidden=false;$('phase').textContent='等待手机响应…';$('result').textContent='';$('total').value=0;$('rows').replaceChildren();
const rows=files.map(f=>{const div=document.createElement('div');div.className='card';const name=document.createElement('p');name.textContent=f.name+' · '+size(f.size);const status=document.createElement('p');status.textContent='等待传输';const progress=document.createElement('progress');progress.max=1;progress.value=0;div.append(name,status,progress);$('rows').append(div);return{status,progress}});
try{const manifest=files.map(f=>({id:uid(),name:(destination?destination+'/':'')+(f.webkitRelativePath||f.name),size:f.size}));const created=await api('/web/uploads','POST',manifest);batch=created.id;if(cancelled){await api('/web/uploads/'+batch,'DELETE');throw Error('已取消')}let state=created.state;while(state==='waiting'&&!cancelled){await new Promise(r=>setTimeout(r,800));state=(await api('/web/uploads/'+batch)).state}if(cancelled||state!=='accepted')throw Error(state==='rejected'?'对方拒绝了请求':'请求已取消或超时');$('phase').textContent='正在发送文件';let sent=0;const total=files.reduce((n,f)=>n+f.size,0);for(let i=0;i<files.length;i++){if(cancelled)throw Error('已取消');await upload(files[i],manifest[i].id,rows[i],sent,total);sent+=files[i].size}$('total').value=1;$('phase').textContent='已完成';$('result').textContent='所有文件已保存到手机';chosen=[];render()}catch(e){$('phase').textContent='传输未完成';$('result').textContent=e.message;if(batch)try{await api('/web/uploads/'+batch,'DELETE')}catch{}}finally{xhr=null;batch=null;$('cancel').hidden=true;$('done').hidden=false}};
$('cancel').onclick=()=>{cancelled=true;xhr?.abort();if(batch)api('/web/uploads/'+batch,'DELETE').catch(()=>{})};$('done').onclick=()=>page('send');
$('edit').onclick=()=>{editing=!editing;render()};
$('settingsTab').onclick=()=>{if(!batch)page(connected?'settings':'login')};
$('chooseDestination').onclick=()=>{const value=prompt('保存到手机爱乐互传下的哪个文件夹？留空使用根目录。',destination);if(value===null)return;if(value.startsWith('/')||value.includes('\\')||value.split('/').some(p=>p==='..'||p.startsWith('.')||p==='待发送')){message('请输入共享目录内的文件夹名称');return}destination=value.replace(/\/$/,'');$('savePath').textContent='文件 › 爱乐互传'+(destination?' / '+destination:'')};
$('copyAddress').onclick=()=>{const input=document.createElement('textarea');input.value=location.origin;document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();message(copied?'连接地址已复制':'连接地址：'+location.origin)};
