'use strict';
const $=id=>document.getElementById(id);
let chosen=[], path='', batch=null, xhr=null, cancelled=false, mode='files', urls=[], connected=false, editing=false, destination='';
const uid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)});
const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
async function recover(){const pending=(await api('/web/uploads')).find(b=>['waiting','accepted'].includes(b.state));$('recover').hidden=!pending;if(pending){message('上一批传输未完成，可结束后重新发送。');$('recover').onclick=async()=>{try{await api('/web/uploads/'+pending.id,'DELETE');$('recover').hidden=true;message('可以重新选择并发送')}catch(e){message(e.message)}}}}
function message(s){$('message').textContent=s}
async function api(url,method='GET',value){const r=await fetch(url,{method,headers:value?{'Content-Type':'application/json'}:{},body:value?JSON.stringify(value):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data}
function page(id){for(const v of ['login','send','files','settings','progress'])$(v).hidden=v!==id;document.body.classList.toggle('transferring',id==='progress');$('sendTab').classList.toggle('active',id==='send');$('settingsTab').classList.toggle('active',id==='settings')}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];$('selected').replaceChildren();$('summary').textContent=chosen.length?'文件：'+chosen.length+' · 大小：'+size(chosen.reduce((n,f)=>n+f.size,0)):'尚未选择文件';$('edit').hidden=!chosen.length;$('edit').textContent=editing?'完成':'编辑';$('clear').hidden=!chosen.length||!editing;chosen.forEach((f,i)=>{const row=document.createElement('div');row.className='file-card';if(f.type.startsWith('image/')){const img=document.createElement('img');img.src=URL.createObjectURL(f);urls.push(img.src);row.append(img)}else{const icon=document.createElement('span');icon.className='file-icon';icon.textContent=/\.(mp3|aiyuepack)$/i.test(f.name)?'♫':'▤';row.append(icon)}const label=document.createElement('span');label.className='file-name';label.textContent=f.webkitRelativePath||f.name;label.title=label.textContent;const bytes=document.createElement('span');bytes.className='file-size';bytes.textContent=size(f.size);const remove=document.createElement('button');remove.textContent='删除';remove.hidden=!editing;remove.onclick=()=>{chosen.splice(i,1);render()};row.append(label,bytes,remove);$('selected').append(row)})}
function select(files,m){chosen=Array.from(files);mode=m;render();message(m==='music'?'音乐包包含 MP3，可同时选择同名 LRC 和 JPG/PNG/WebP 封面。缺少附件也可发送。':'')}
$('choose').onclick=()=>$('fileInput').click();$('folder').onclick=()=>$('folderInput').click();$('music').onclick=()=>$('musicInput').click();
for(const [id,m] of [['fileInput','files'],['folderInput','files'],['musicInput','music']])$(id).onchange=e=>{select(e.target.files,m);e.target.value=''};
$('clear').onclick=()=>{chosen=[];render()};$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();select(e.dataTransfer.files,'files')};
$('connect').onclick=async()=>{try{await api('/web/session','POST',{code:$('code').value});$('code').value='';connected=true;page('send');message('已连接');await recover();const info=await api('/web/info');$('deviceName').textContent=info.alias;$('version').textContent='版本 '+info.version+' · 浏览器已连接手机'}catch(e){message(e.message)}};
$('sendTab').onclick=()=>{if(!batch)page(connected?'send':'login')};$('filesTab').onclick=()=>{if(!batch&&connected)load()};
$('refresh').onclick=async()=>{const b=$('refresh');b.classList.remove('spin');void b.offsetWidth;b.classList.add('spin');try{await api('/web/files');message('手机已连接')}catch(e){message(e.message)}};
async function load(){try{const list=await api('/web/files?path='+encodeURIComponent(path));page('files');$('path').textContent=path||'爱乐互传';$('listing').replaceChildren();for(const f of list){const row=document.createElement('div');row.className='row';const label=document.createElement('div');label.textContent=(f.directory?'📁 ':'📄 ')+f.name+(f.directory?'':' · '+size(f.size));const action=document.createElement(f.directory?'button':'a');action.textContent=f.directory?'打开':'下载';if(f.directory)action.onclick=()=>{path=f.path;load()};else{action.href='/web/download?path='+encodeURIComponent(f.path);action.download=f.name}row.append(label,action);$('listing').append(row)}}catch(e){message(e.message)}}
$('reload').onclick=load;$('up').onclick=()=>{path=path.split('/').slice(0,-1).join('/');load()};$('mkdir').onclick=async()=>{const name=prompt('文件夹名称');if(!name)return;try{await api('/web/folders','POST',{path:(path?path+'/':'')+name});await load()}catch(e){message(e.message)}};
function upload(file,id,row,previous,total){return new Promise((resolve,reject)=>{xhr=new XMLHttpRequest();xhr.open('PUT','/web/uploads/'+batch+'/'+id);xhr.upload.onprogress=e=>{row.progress.value=e.loaded/file.size||0;$('total').value=(previous+e.loaded)/total||0;row.status.textContent='正在传输 '+size(e.loaded)+' / '+size(file.size)};xhr.onload=()=>{if(xhr.status===200){row.progress.value=1;row.status.textContent='已保存到文件 › 爱乐互传';resolve()}else reject(Error('保存失败，请重试'))};xhr.onerror=()=>reject(Error('连接中断'));xhr.onabort=()=>reject(Error('已取消'));xhr.timeout=0;xhr.ontimeout=()=>reject(Error('传输超时'));xhr.send(file)})}
$('device').onclick=async()=>{if(!chosen.length){message('请至少选择一个文件。');return}cancelled=false;let files;try{files=mode==='music'?await musicPackages(chosen):chosen}catch(e){message(e.message);return}
page('progress');$('done').hidden=true;$('cancel').hidden=false;$('phase').textContent='等待手机响应…';$('result').textContent='';$('total').value=0;$('rows').replaceChildren();
const rows=files.map(f=>{const div=document.createElement('div');div.className='card';const name=document.createElement('p');name.textContent=f.name+' · '+size(f.size);const status=document.createElement('p');status.textContent='等待传输';const progress=document.createElement('progress');progress.max=1;progress.value=0;div.append(name,status,progress);$('rows').append(div);return{status,progress}});
try{const manifest=files.map(f=>({id:uid(),name:(destination?destination+'/':'')+(f.webkitRelativePath||f.name),size:f.size}));const created=await api('/web/uploads','POST',manifest);batch=created.id;if(cancelled){await api('/web/uploads/'+batch,'DELETE');throw Error('已取消')}let state=created.state;while(state==='waiting'&&!cancelled){await new Promise(r=>setTimeout(r,800));state=(await api('/web/uploads/'+batch)).state}if(cancelled||state!=='accepted')throw Error(state==='rejected'?'对方拒绝了请求':'请求已取消或超时');$('phase').textContent='正在发送文件';let sent=0;const total=files.reduce((n,f)=>n+f.size,0);for(let i=0;i<files.length;i++){if(cancelled)throw Error('已取消');await upload(files[i],manifest[i].id,rows[i],sent,total);sent+=files[i].size}$('total').value=1;$('phase').textContent='已完成';$('result').textContent='所有文件已保存到手机';chosen=[];render()}catch(e){$('phase').textContent='传输未完成';$('result').textContent=e.message;if(batch)try{await api('/web/uploads/'+batch,'DELETE')}catch{}}finally{xhr=null;batch=null;$('cancel').hidden=true;$('done').hidden=false}};
$('cancel').onclick=()=>{cancelled=true;xhr?.abort();if(batch)api('/web/uploads/'+batch,'DELETE').catch(()=>{})};$('done').onclick=()=>page('send');
// ZIP STORE entries are Blob parts, so large MP3 data is never concatenated in memory.
async function musicPackages(files){const audios=files.filter(f=>/\.mp3$/i.test(f.name));if(!audios.length)throw Error('音乐包至少需要一个 MP3 文件');const result=[];for(const audio of audios){const stem=audio.name.replace(/\.mp3$/i,'');const find=ext=>files.find(f=>f.name.replace(/\.[^.]+$/,'').toLowerCase()===stem.toLowerCase()&&ext.test(f.name));const lyrics=find(/\.lrc$/i);const cover=find(/\.(jpg|jpeg|png|webp)$/i)||files.find(f=>/^cover\.(jpg|jpeg|png|webp)$/i.test(f.name));const manifest={title:stem,audioPath:'audio/'+audio.name,lyricsPath:lyrics?'lyrics/'+lyrics.name:null,coverPath:cover?'cover/'+cover.name:null};const entries=[{name:manifest.audioPath,data:audio}];if(lyrics)entries.push({name:manifest.lyricsPath,data:lyrics});if(cover)entries.push({name:manifest.coverPath,data:cover});entries.push({name:'manifest.json',data:new Blob([JSON.stringify(manifest)])});result.push(new File([await zip(entries)],stem+'.aiyuepack',{type:'application/zip'}))}return result}
async function zip(entries){const parts=[],central=[];let offset=0;for(const e of entries){if(e.data.size>0xffffffff)throw Error('单首音乐超过音乐包 4 GB 限制');const name=new TextEncoder().encode(e.name);let crc=0xffffffff;for(let p=0;p<e.data.size;p+=65536){const chunk=new Uint8Array(await e.data.slice(p,p+65536).arrayBuffer());for(const b of chunk){crc^=b;for(let k=0;k<8;k++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}}crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,e.data.size,true);v.setUint32(22,e.data.size,true);v.setUint16(26,name.length,true);parts.push(h,name,e.data);const c=new Uint8Array(46),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint32(16,crc,true);d.setUint32(20,e.data.size,true);d.setUint32(24,e.data.size,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);central.push(c,name);offset+=30+name.length+e.data.size}const length=central.reduce((n,p)=>n+p.length,0);if(offset+length>0xffffffff)throw Error('音乐包过大');const end=new Uint8Array(22),d=new DataView(end.buffer);d.setUint32(0,0x06054b50,true);d.setUint16(8,entries.length,true);d.setUint16(10,entries.length,true);d.setUint32(12,length,true);d.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
$('edit').onclick=()=>{editing=!editing;render()};
$('settingsTab').onclick=()=>{if(!batch)page(connected?'settings':'login')};
$('chooseDestination').onclick=()=>{const value=prompt('保存到手机爱乐互传下的哪个文件夹？留空使用根目录。',destination);if(value===null)return;if(value.startsWith('/')||value.includes('\\')||value.split('/').some(p=>p==='..'||p.startsWith('.')||p==='待发送')){message('请输入共享目录内的文件夹名称');return}destination=value.replace(/\/$/,'');$('savePath').textContent='文件 › 爱乐互传'+(destination?' / '+destination:'')};
$('copyAddress').onclick=()=>{const input=document.createElement('textarea');input.value=location.origin;document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();message(copied?'连接地址已复制':'连接地址：'+location.origin)};
